/*******************************************************************************
* Copyright 2014 eTilbudsavis
* 
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* 
*   http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/
package com.eTilbudsavis.etasdk.EtaObjects;

import java.io.Serializable;

import org.json.JSONException;
import org.json.JSONObject;

import android.os.Parcel;
import android.os.Parcelable;

import com.eTilbudsavis.etasdk.Eta;
import com.eTilbudsavis.etasdk.Log.EtaLog;
import com.eTilbudsavis.etasdk.Utils.Api.JsonKey;
import com.eTilbudsavis.etasdk.Utils.Json;

/**
 * EtaErnObject has the advantage of having an Etilbudsavis Resource Name (ERN), that is a <i>unique</i> identifier 
 * for this object in the API v2.
 * 
 * @author Danny Hvam - danny@etilbudsavis.dk
 *
 */
public class ErnObject<T> implements Serializable, Parcelable {
	
	public interface Ern<T> {

		/**
		 * Get the id for this object.
		 * @return A {@link String}, or <code>null</code>
		 */
		public String getId();

		/**
		 * Set the id for this object.
		 * @return A {@link String}, or <code>null</code>
		 */
		public T setId(String id);

		/**
		 * Get the Etilbudsavis Resource Name (ERN) for this object.
		 * <p>ERN is a <i>unique</i> identifier for objects in the eTilbudsavis API v2, and should in most cases be 
		 * generated by the server, and <i>not</i> by the client</p>
		 * @return A {@link String}, or null
		 */
		public String getErn();

		/**
		 * Set the Etilbudsavis Resource Name (ERN) for this object.
		 * <p>ERN is a <i>unique</i> identifier for objects in the eTilbudsavis API v2, and should in most cases be 
		 * generated by the server, and <i>not</i> by the client</p>
		 * @param ern A non-<code>null</code> String
		 * @return
		 */
		public T setErn(String ern);
		
	}
	
	private static final long serialVersionUID = -1549391274049017721L;

	public static final String TAG = Eta.TAG_PREFIX + ErnObject.class.getSimpleName();
	
	private final String mErnClass;
	private String mId;
	private String mErn;
	
	public ErnObject(String ernClass) {
		mErnClass = ernClass;
	}
	
	@SuppressWarnings("unchecked")
	public T setId(String id) {
		mId = id;
		mErn = String.format("ern:%s:%s", mErnClass, id);
		return (T)this;
	}
	
	public String getId() {
		return mId;
	}
	
	@SuppressWarnings("unchecked")
	public T setErn(String ern) {
		if (ern != null) {
			mErn = ern;
			String[] parts = mErn.split(":");
			mId = parts[parts.length-1];
		}
		return (T)this;
	}
	
	public String getErn() {
		return mErn;
	}
	
	public JSONObject toJSON() {
		JSONObject o = new JSONObject();
		try {
			o.put(JsonKey.ID, Json.nullCheck(getId()));
			o.put(JsonKey.ERN, Json.nullCheck(getErn()));
		} catch (JSONException e) {
			EtaLog.e(TAG, "", e);
		}
		return o;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((mErn == null) ? 0 : mErn.hashCode());
		result = prime * result + ((mId == null) ? 0 : mId.hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ErnObject<?> other = (ErnObject<?>) obj;
		if (mErn == null) {
			if (other.mErn != null)
				return false;
		} else if (!mErn.equals(other.mErn))
			return false;
		if (mId == null) {
			if (other.mId != null)
				return false;
		} else if (!mId.equals(other.mId))
			return false;
		return true;
	}

	public int describeContents() {
		// TODO Auto-generated method stub
		return 0;
	}

	public void writeToParcel(Parcel dest, int flags) {
		// TODO Auto-generated method stub
		
	}
	
}
