package com.eTilbudsavis.etasdk.model.interfaces;

public interface IErn<T> {

	public static final String TYPE_CATALOG = "catalog";
	public static final String TYPE_DEALER = "dealer";
	public static final String TYPE_OFFER = "offer";
	public static final String TYPE_SHOPPINGLIST = "shopping:list";
	public static final String TYPE_STORE = "store";
	public static final String TYPE_USER = "user";
	public static final String TYPE_COUNTRY = "country";
	
	/**
	 * Get the id for this object.
	 * @return A {@link String}, or <code>null</code>
	 */
	public String getId();

	/**
	 * Set the id for this object.
	 * @return A {@link String}, or <code>null</code>
	 */
	public T setId(String id);

	/**
	 * Get the Etilbudsavis Resource Name (ERN) for this object.
	 * <p>ERN is a <i>unique</i> identifier for objects in the eTilbudsavis API v2, and should in most cases be 
	 * generated by the server, and <i>not</i> by the client</p>
	 * @return A {@link String}, or null
	 */
	public String getErn();

	/**
	 * Set the Etilbudsavis Resource Name (ERN) for this object.
	 * <p>ERN is a <i>unique</i> identifier for objects in the eTilbudsavis API v2, and should in most cases be 
	 * generated by the server, and <i>not</i> by the client</p>
	 * @param ern A String
	 * @return A string, or null
	 */
	public T setErn(String ern);
	
	/**
	 * Returns a ERN type. If a type doesn't exist, the id will be returned
	 * @return A string, or null
	 */
	public String getErnType();
	
}
