package com.eTilbudsavis.etasdk.EtaObjects.Interface;

public interface IErn<T> {
	
	/**
	 * Get the id for this object.
	 * @return A {@link String}, or <code>null</code>
	 */
	public String getId();

	/**
	 * Set the id for this object.
	 * @return A {@link String}, or <code>null</code>
	 */
	public T setId(String id);

	/**
	 * Get the Etilbudsavis Resource Name (ERN) for this object.
	 * <p>ERN is a <i>unique</i> identifier for objects in the eTilbudsavis API v2, and should in most cases be 
	 * generated by the server, and <i>not</i> by the client</p>
	 * @return A {@link String}, or null
	 */
	public String getErn();

	/**
	 * Set the Etilbudsavis Resource Name (ERN) for this object.
	 * <p>ERN is a <i>unique</i> identifier for objects in the eTilbudsavis API v2, and should in most cases be 
	 * generated by the server, and <i>not</i> by the client</p>
	 * @param ern A non-<code>null</code> String
	 * @return
	 */
	public T setErn(String ern);
	
}
